### ISSUE TITLE
Some blocks placed on different blocks may cause the game to crash

### ISSUE THREAD

**Issue by fzrdwa123456** [ACGaming/MrCrayfishFurnitureModRebuilt#1]
**Describe the bug**

When the item 'cfm:wall_cabinet' is placed on thin snow, the game will crash. I didn't mean to do it. This is a bug I found when I was building the game map. The original mod also had this problem.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

https://mclo.gs/mJ51D9q

**To Reproduce**
If applicable, the steps to reproduce the behavior:

I will upload a video to explain everything.

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.12.2，forge:14.23.5.2860
- Mod Version:6.4.1

**Comment by fzrdwa123456** [comment]
https://github.com/ACGaming/MrCrayfishFurnitureModLegacy/assets/130232431/c5af01bf-61df-4343-9f1e-7b24b2a23bc6

**Comment by fzrdwa123456** [comment]
Currently, I don't know if other blocks will have the same issue, as this problem was discovered by accident.

**Comment by fzrdwa123456** [comment]
[crash-2024-05-10_06.54.16-client.txt](https://github.com/ACGaming/MrCrayfishFurnitureModLegacy/files/15268529/crash-2024-05-10_06.54.16-client.txt)

**Comment by fzrdwa123456** [comment]
Because the original mod is no longer being maintained, and only you can solve this issue now. Thank you if you can fix it.

**Comment by ACGaming** [comment]
> snownee.snow.ModSnowBlock.func_180639_a(ModSnowBlock.java:515)

It's very likely that [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) is causing the issue, does it still happen when that mod is disabled/removed?

**Comment by fzrdwa123456** [comment]
> > snownee.snow.ModSnowBlock.func_180639_a(ModSnowBlock.java:515)
> 
> It's very likely that [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) is causing the issue, does it still happen when that mod is disabled/removed?

I followed your method and it didn't crash. So Snow! Real Magic! is the problem. Can you make Snow! Real Magic! compatible with this mod and work together normally? Because I really like Snow! Real Magic!

**Comment by ACGaming** [comment]
Although it would be best if Snow! Real Magic! would add a safety check for the `canPlaceBlockOnSide()` method but I can also work around the issue within MrCrayfish's Furniture Mod.
