### ISSUE TITLE
"Dark Oak Upgraded Fence" and "Dark Oak Fence" visually connects to Air when wearing "Leggings of the Burning Mantle"

### ISSUE THREAD

**Issue by Lumpous** [ACGaming/MrCrayfishFurnitureModRebuilt#5]
[https://github.com/xJon/The-1.12.2-Pack/issues/982](https://github.com/xJon/The-1.12.2-Pack/issues/982)
Java on local PC:
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)

Java on Server:
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (build 1.8.0_422-8u422-b05-1~22.04-b05)
OpenJDK 64-Bit Server VM (build 25.422-b05, mixed mode)

Affected mods:
thaumictinkerer-1.12.2-5.7.1-Unofficial.jar
cfm-legacy-1.12.2-6.5.0.jar

Issue is repeatable in both SP and MP

---
Whenever i come close or look at a "Dark Oak Upgraded Fence" or "Dark Oak Fence" while wearing the "Leggings of the Burning Mantle", the fence visualy connects to anything on all 4 sides - even to air.
For this to happen, the characters head has to be on the same level as the fence and in at least 6 blocks of range.
Tried also without the enchantment - same behaviour.

This visual connection is also only temporary leaving the visible range and returning reverts the visual appearence back to normal.
![image](https://github.com/user-attachments/assets/d859e588-e9d6-4d40-a1c2-612c742bf492)
[short video #1](https://gyazo.com/5486263fb720095d7cad529db6782a0f)
[short video #2](https://gyazo.com/56e1fc11b5c965d4f2900b9b1bfde74f)

![image](https://github.com/user-attachments/assets/bd4bbfa8-ab84-42f6-b6c7-4a75deee2a96)

**Comment by ACGaming** [comment]
As stated in [this comment](https://github.com/xJon/The-1.12.2-Pack/issues/982#issuecomment-2407765465), this applies to any fence/pane block, thus can't be fixed from within this mod.
